[features]
seeds = false
skip-lint = false

[programs.devnet]
distri_ai = "6yFTDdiS1W9T9yg6YejkwKggkEE4NYqdSSzVqQvuLn16"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "target/deploy/distri_ai-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
