[features]
seeds = false
skip-lint = false

[programs.devnet]
distri_ai = "8WxFh7ZtvTP1587yvyweoRMt41hCHMsmM48PTbZKM4tY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=fb4bcaf8-c252-40bd-87d2-7a9edfa332e7"
wallet = "target/deploy/distri_ai-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
